name: springsecurity # nameを指定することによってDockerのコンテナ名を指定することができます。

services:
  postgres:
    image: postgres:16
    container_name: springsecurity-db
    environment:
      POSTGRES_DB: springsecurity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5433:5432"
    volumes:
      - springsecurity-data:/var/lib/postgresql/data

volumes:
  springsecurity-data:
